### ISSUE TITLE
太极阴ADB命令出错。

### ISSUE THREAD

**Issue by xesp** [taichi-framework/TaiChi#1088]
## 什么问题
执行太极阴的ADB命令的时候出现错误提示。
（请简要说明你遇到的问题）

## 详细情况
C:\Users\xesp>adb shell dpm set-device-owner me.weishu.exp/.DeviceAdmin
* daemon not running; starting now at tcp:5037
* daemon started successfully
java.lang.IllegalStateException: Not allowed to set the device owner because the
re are already several users on the device
        at android.os.Parcel.createException(Parcel.java:1958)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDev
icePolicyManager.java:5874)
        at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:176)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:106)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.dpm.Dpm.main(Dpm.java:41)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCan
SetDeviceOwnerLocked(DevicePolicyManagerService.java:7909)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceO
wner(DevicePolicyManagerService.java:7202)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyM
anager.java:1095)
        at android.os.Binder.execTransact(Binder.java:739)
（请尽可能**详细地**说明你遇到了什么问题，以及必要的复现步骤）

Magisk 版本：无
太极 Magisk 模块版本：无
太极APP版本：5.8.2-1497
开启的 Xposed 模块：
Xposed模块版本：
开启的其他 Magisk 模块：(无）
其他 Magisk 模块版本：（无）
手机型号：魅族16xs
ROM版本：flyme 8

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
> Not allowed to set the device owner because the
re are already several users on the device

账号没删干净
