### ISSUE TITLE
Bug report: [App Creation] [DexReWriter] Unsigned short value out of range: 65536

### ISSUE THREAD

**Issue by akhilkedia** [taichi-framework/TaiChi#1120]
**Describe the bug**
For some apks, "Create App" with Taichi causes Taichi to crash and the app is not created with the error - `Unsigned short value out of range: 65536`

**To Reproduce**
1. Install Taichi
2. Click Create App (+)
3. Click (+)
4. Select this apk from here - [apkpure](https://apkpure.com/cgv/com.cgv.android.movieapp/download/476-APK) or [Google play store](https://play.google.com/store/apps/details?id=com.cgv.android.movieapp&hl=en)

**Expected behavior**
Taichi install the app and does not crash.

**Smartphone (please complete the following information):**
Magisk version：N/A (non-root)
TaiChi-Magisk module version：N/A
TaiChi version：6.0.3-2369
Which Xposed modules are enabled ?：None
Xposed modules version：N/A
Which Magisk modules are enabled ?：N/A
Magisk modules version：N/A
Device ：Samsung Galaxy S20+
ROM：Stock, Factory Android 10

**Additional context**
Perhaps the error is because of the number of methods exceeding 65K limit for dex?
This seems similar to this issue - https://github.com/taichi-framework/TaiChi/issues/456

 Here is the relevant log - 
````
2020-04-03 20:24:29.759 21143-28025/? W/System.err: me.bmr: Exception occurred while writing code_item for method Lorg/simpleframework/xml/DefaultType;->values()[Lorg/simpleframework/xml/DefaultType;
2020-04-03 20:24:29.759 21143-28025/? W/System.err:     at me.bkv.ˏ(SourceFile:917)
2020-04-03 20:24:29.759 21143-28025/? W/System.err:     at me.bkv.ˏ(SourceFile:341)
2020-04-03 20:24:29.759 21143-28025/? W/System.err:     at me.bkv.ˏ(SourceFile:297)
2020-04-03 20:24:29.759 21143-28025/? W/System.err:     at me.blx.ˏ(SourceFile:98)
2020-04-03 20:24:29.759 21143-28025/? W/System.err:     at me.awb.ˏ(SourceFile:290)
2020-04-03 20:24:29.759 21143-28025/? W/System.err:     at me.weishu.exp.core.DexReWriter.rewrite(SourceFile:347)
2020-04-03 20:24:29.759 21143-28025/? W/System.err:     at me.weishu.exp.core.DexReWriter.rewrite2(SourceFile:122)
2020-04-03 20:24:29.759 21143-28025/? W/System.err:     at me.weishu.exp.core.Creator.nativeCreate(Native Method)
2020-04-03 20:24:29.759 21143-28025/? W/System.err:     at me.weishu.exp.core.Creator.ˏ(SourceFile:81)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at me.weishu.exp.ui.MainActivity.ˉ(SourceFile:971)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at me.weishu.exp.ui.MainActivity.lambda$qzqc7nV5gxFKloG0_LYQ_gDOwrs(Unknown Source:0)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at me.weishu.exp.ui.-$$Lambda$MainActivity$qzqc7nV5gxFKloG0_LYQ_gDOwrs.call(Unknown Source:4)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-04-03 20:24:29.760 21143-28025/? W/System.err: Caused by: me.bmr: Error while writing instruction at code offset 0x2
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at me.bkv.ˏ(SourceFile:1190)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at me.bkv.ˏ(SourceFile:913)
2020-04-03 20:24:29.760 21143-28025/? W/System.err: 	... 17 more
2020-04-03 20:24:29.760 21143-28025/? W/System.err: Caused by: me.bmr: Unsigned short value out of range: 65536
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at me.bku.ʻ(SourceFile:116)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at me.bla.ˏ(SourceFile:356)
2020-04-03 20:24:29.760 21143-28025/? W/System.err:     at me.bkv.ˏ(SourceFile:1150)
2020-04-03 20:24:29.760 21143-28025/? W/System.err: 	... 18 more
2020-04-03 20:24:29.761 21143-28025/? W/System.err: me.awb$ʽ: /data/user/0/me.weishu.exp/cache/apks/com.cgv.android.movieapp_1585913053637/classes.dex is not an apk, dex, odex or oat file.
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.awb.ˏ(SourceFile:135)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.core.DexReWriter.rewrite(SourceFile:211)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.core.Creator.nativeCreate(Native Method)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.core.Creator.ˏ(SourceFile:81)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.ui.MainActivity.ˉ(SourceFile:971)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.ui.MainActivity.lambda$qzqc7nV5gxFKloG0_LYQ_gDOwrs(Unknown Source:0)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.ui.-$$Lambda$MainActivity$qzqc7nV5gxFKloG0_LYQ_gDOwrs.call(Unknown Source:4)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-04-03 20:24:29.761 21143-28025/? W/System.err: me.weishu.exp.core.CreateFailedException: r d f..
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.core.Creator.nativeCreate(Native Method)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.core.Creator.ˏ(SourceFile:81)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.ui.MainActivity.ˉ(SourceFile:971)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.ui.MainActivity.lambda$qzqc7nV5gxFKloG0_LYQ_gDOwrs(Unknown Source:0)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at me.weishu.exp.ui.-$$Lambda$MainActivity$qzqc7nV5gxFKloG0_LYQ_gDOwrs.call(Unknown Source:4)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-04-03 20:24:29.761 21143-28025/? W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-04-03 20:24:29.796 21143-28025/? I/DexReWriter: performance s1: 0, s2: 15, s3: 1, s4: 19
2020-04-03 20:24:29.797 21143-28025/? W/DexReWriter: dex: /data/user/0/me.weishu.exp/cache/apks/com.cgv.android.movieapp_1585913053637/classes2.dex has no entry class, return
````

**Comment by tiann** [comment]
fixed in version 6.4
