### ISSUE TITLE
MAGISK中启用TAICHI 6.2.3后，钉钉工作平台打不开。

### ISSUE THREAD

**Issue by wzs1598** [taichi-framework/TaiChi#1216]
如题，如果在MAGISK中启用TAICHI 6.2.3后，钉钉工作平台就打不开。如果关闭后重启，钉钉工作平台就没有任何问题。试过删除钉钉再重装、清空太极设置、钉钉添加到太极等多种方式。只要启用，钉钉工作平台都无法登录。

**Comment by wzs1598** [comment]
补充一下：MAGISK中启用太极后，支付宝中的小游戏如养鸡等，都会出现卡顿现象，关闭则正常。

MIUI12.5/MAGISK21.4/太极6.4.0.09021214518

**Comment by wzs1598** [comment]
经逐版本测试，5.1.36及以前版本一切正常。后续版本不能打开。

**Comment by zhaoxilingcheng** [comment]
经测试， 手中的小米miui有问题， 版本为12.5中的开发内测版本。
其他手机无此问题。

**Comment by csgka1** [comment]
各种方法都试过，折腾了一上午终于找到了这里，破案了……

应该是一个和ROM无关的BUG，我的 Redmi K20 Pro 刷了 Havoc OS@Android 11 也遇到了这个问题。
只有当 Magisk 启用太极插件之后才会出现该问题，否则不会出现。

国内版 和 Google Play 版都有BUG，国内版会提示加载失败, Play 版则直接闪退或者重启 MainActivity，此外打卡界面和 设置-安全中心 都会出现这个 BUG。目测问题出现在钉钉的 MiniApp 模块。

贴一下闪退时从 ADB 提取的错误日志：
```log
06-15 11:41:59.335 14563 15640 W ANet.RemoteGetter: 	at com.alibaba.android.rimet.biz.update.CheckVersionRequest.a(CheckVersionRequest.java:83)
06-15 11:42:00.761 14563 14563 W URGENT  : type=1400 audit(0.0:1737): avc: granted { execute } for path="/data/user/0/com.alibaba.android.rimet/app_ucmsdk/decompresses2/_1188849942/13767477_315504000000/lib/libjsi.so" dev="sda31" ino=5184 scontext=u:r:untrusted_app_29:s0:c103,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c103,c257,c512,c768 tclass=file app=com.alibaba.android.rimet
06-15 11:42:01.831 16244 16244 W URGENT  : type=1400 audit(0.0:1742): avc: denied { search } for name="battery" dev="sysfs" ino=68900 scontext=u:r:untrusted_app_29:s0:c103,c257,c512,c768 tcontext=u:object_r:sysfs_battery_supply:s0 tclass=dir permissive=0 app=com.alibaba.android.rimet
06-15 11:42:01.831 16244 16244 W URGENT  : type=1400 audit(0.0:1744): avc: denied { read } for name="power_supply" dev="sysfs" ino=47827 scontext=u:r:untrusted_app_29:s0:c103,c257,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=dir permissive=0 app=com.alibaba.android.rimet
06-15 11:42:01.831 16244 16244 W URGENT  : type=1400 audit(0.0:1746): avc: denied { search } for name="battery" dev="sysfs" ino=68900 scontext=u:r:untrusted_app_29:s0:c103,c257,c512,c768 tcontext=u:object_r:sysfs_battery_supply:s0 tclass=dir permissive=0 app=com.alibaba.android.rimet
06-15 11:42:03.111 14571 15079 I TetheringManager: registerTetheringEventCallback:com.alibaba.android.rimet
06-15 11:42:03.120 14563 16236 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc00699b82c000 in tid 16236 (URGENT), pid 14563 (a.android.rimet)
06-15 11:42:03.406 16522 16522 F DEBUG   : pid: 14563, tid: 16236, name: URGENT  >>> com.alibaba.android.rimet <<<
06-15 11:42:03.676 16522 16522 F DEBUG   :       #00 pc 0000000000049ba0  /data/user/0/com.alibaba.android.rimet/app_ucmsdk/decompresses2/_1188849942/13767477_315504000000/lib/libjsi.so
06-15 11:42:03.676 16522 16522 F DEBUG   :       #01 pc 000000000004909c  /data/user/0/com.alibaba.android.rimet/app_ucmsdk/decompresses2/_1188849942/13767477_315504000000/lib/libjsi.so
06-15 11:42:03.676 16522 16522 F DEBUG   :       #02 pc 000000000004885c  /data/user/0/com.alibaba.android.rimet/app_ucmsdk/decompresses2/_1188849942/13767477_315504000000/lib/libjsi.so
06-15 11:42:03.676 16522 16522 F DEBUG   :       #03 pc 0000000000047698  /data/user/0/com.alibaba.android.rimet/app_ucmsdk/decompresses2/_1188849942/13767477_315504000000/lib/libjsi.so
06-15 11:42:03.677 16522 16522 F DEBUG   :       #04 pc 0000000000047998  /data/user/0/com.alibaba.android.rimet/app_ucmsdk/decompresses2/_1188849942/13767477_315504000000/lib/libjsi.so
06-15 11:42:03.677 16522 16522 F DEBUG   :       #05 pc 0000000000011cf8  /data/user/0/com.alibaba.android.rimet/app_ucmsdk/decompresses2/_1188849942/13767477_315504000000/lib/libjsi.so
06-15 11:42:03.677 16522 16522 F DEBUG   :       #06 pc 00000000001d208c  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.odex (art_jni_trampoline+188)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #13 pc 000000000334f184  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.jsi.standard.b.a+380)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #19 pc 000000000334dbec  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.jsi.standard.JSEngine.loadSo+60)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #25 pc 0000000003203ac8  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.ariver.v8worker.V8Worker.staticInit+204)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #31 pc 0000000003204784  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.ariver.v8worker.V8Worker.<init>+660)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #34 pc 00000000038a2628  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.lightapp.runtime.ariver.engine.h5engine.webview.serviceworker.TheOneV8Worker.<init>+12)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #37 pc 00000000038bb6a4  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.lightapp.runtime.ariver.manager.TheOneWorkerPoolManager.createWorker+184)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #40 pc 00000000038bb768  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.lightapp.runtime.ariver.manager.TheOneWorkerPoolManager.generateWorker+80)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #43 pc 000000000389f1aa  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.lightapp.runtime.ariver.engine.h5engine.webview.WebViewEngineProxy.prepareWorker+34)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #46 pc 000000000389f0c8  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.lightapp.runtime.ariver.engine.h5engine.webview.WebViewEngineProxy.access$100)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #49 pc 000000000389eeda  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.lightapp.runtime.ariver.engine.h5engine.webview.WebViewEngineProxy$2.run+14)
06-15 11:42:03.677 16522 16522 F DEBUG   :       #52 pc 00000000038c1262  /data/app/~~BnXzY56O0Nrox9N0UG379w==/com.alibaba.android.rimet-LpeJCzgc1W8s_ntv5f0KQg==/oat/arm64/base.vdex (com.alibaba.lightapp.runtime.ariver.proxy.TheOneExecutorService$6$2.run+158)
```


另：很神奇的是刷了其他的 ROM, 钉钉还是会把手机识别成小米手机，改 `settings.device_name` 是没用的。通知设置里会出现小米手机设置，Log 中也有体现，它会锲而不舍地去访问一个奇怪的 `setStatusBarFontForMiui` 方法：

```log
06-15 11:53:05.325 25823 25823 W System.err: 	at com.alibaba.android.dingtalkui.activity.BaseUIActivity.setStatusBarFontForMiui(BaseUIActivity.java:586)
06-15 11:53:05.325 25823 25823 W System.err: 	at com.alibaba.android.dingtalkui.activity.BaseUIActivity.setupImmersiveStatusBar(BaseUIActivity.java:521)
06-15 11:53:05.354 25823 25823 W System.err: 	at com.alibaba.android.dingtalkbase.widgets.AvatarImageView.a(AvatarImageView.java:359)
06-15 11:53:05.354 25823 25823 W System.err: 	at com.alibaba.android.dingtalkbase.widgets.AvatarImageView.a(AvatarImageView.java:247)
06-15 11:53:05.354 25823 25823 W System.err: 	at com.alibaba.android.dingtalkbase.widgets.AvatarImageView.setRoundRectAvatar(AvatarImageView.java:207)
06-15 11:53:05.354 25823 25823 W System.err: 	at com.alibaba.android.dingtalkbase.widgets.AvatarImageView.setAvatar(AvatarImageView.java:227)
06-15 11:53:05.354 25823 25823 W System.err: 	at com.alibaba.android.dingtalkbase.widgets.AvatarImageView.setAvatar(AvatarImageView.java:201)
06-15 11:53:07.238 25823 25947 E LaunchHomeActivity: com.alibaba.dingtalk.safeguard.protect.DSGException: DSGError,get basic DataErrorCode=21
06-15 11:53:16.026  1913  2764 W ActivityManager: Scheduling restart of crashed service com.alibaba.android.rimet/com.alibaba.android.dingtalkbase.service.DDEudemonService in 1800000ms for start-requested
```

不知道和BUG有没有关系，总之先贴出来吧。

**Comment by tiann** [comment]
可临时使用此版本：https://taichi.lanzoui.com/i8O6Nppvyuf

**Comment by zhuhonglei** [comment]
> 可临时使用此版本：https://taichi.lanzoui.com/i8O6Nppvyuf

一加9R上，此版本无限重启
