### ISSUE TITLE
请求增加对MyPrivacy的支持

### ISSUE THREAD

**Issue by wuzunweiwang** [taichi-framework/TaiChi#133]
## 模块名字
MyPrivacy
## 模块用途
可以禁止应用读取应用列表权限，禁止获取网络数据，禁止GPS定位
## 模块版本号
2.0.1
## 模块安装包
[MyPrivacy.zip](https://github.com/tiann/EXposed/files/2816793/MyPrivacy.zip)

**Comment by tiann** [comment]
这个模块的代码有严重 BUG，功能几乎全部失效，以下是错误日志：

```txt
2019-02-25 11:52:39.797 16359-16359/? E/Xposed: java.lang.NoSuchMethodError: com.jasperhale.myprivacy.XposedHook.Hook.LocationManager#addGpsStatusListener(android.location.GpsStatus.Listener)#exact
        at de.robv.android.xposed.XposedHelpers.findMethodExact(SourceFile:344)
        at de.robv.android.xposed.XposedHelpers.findAndHookMethod(SourceFile:185)
        at com.jasperhale.myprivacy.XposedHook.Hook.LocationManager.addGpsStatusListener(LocationManager.java:61)
        at com.jasperhale.myprivacy.XposedHook.Hook.LocationManager.handle(LocationManager.java:32)
        at com.jasperhale.myprivacy.XposedHook.XposedModule.handleLoadPackage(XposedModule.java:35)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(SourceFile:34)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(SourceFile:61)
        at de.robv.android.xposed.callbacks.XCallback.callAll(SourceFile:106)
        at me.weishu.exposed.ExposedBridge.a(SourceFile:819)
        at me.weishu.exposed.ExposedBridge.loadModule(SourceFile:757)
        at me.weishu.exposed.ExposedBridge.initNative(Native Method)
        at me.weishu.exposed.ExposedBridge.init(SourceFile:177)
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.taichi.MagiskInit.b(Unknown Source:291)
        at me.weishu.taichi.MagiskInit.a(Unknown Source:0)
        at me.weishu.taichi.MagiskInit$1$1.handleMessage(Unknown Source:14)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

查看代码发现，这里有一处笔误：

```java
    private static void addGpsStatusListener() {
        XposedBridge.log("MyprivacyHook" + LocationManager.lpparam.packageName + "LM" + "addNmeaListener");
        XposedHelpers.findAndHookMethod(LocationManager.class, "addGpsStatusListener", new Object[]{GpsStatus$Listener.class, new XC_MethodHook() {
            protected void afterHookedMethod(XC_MethodHook$MethodHookParam arg7) {
                if(arg7.args[0] != null) {
                    XposedHelpers.callMethod(arg7.args[0], "onGpsStatusChanged", new Object[]{Integer.valueOf(1)});
                    XposedHelpers.callMethod(arg7.args[0], "onGpsStatusChanged", new Object[]{Integer.valueOf(3)});
                }
            }
        }});
    }
```

LocationManager 应该是  Android 系统的 `android.location.LocationManager`

这并非太极的问题，如果模块作者不修复此bug，这个插件基本等于无用。

**Comment by tiann** [comment]
https://github.com/Jasper-1024/MyPrivacy/issues/3
