### ISSUE TITLE
Bug report: 阴阳之门报错

### ISSUE THREAD

**Issue by Nesxc** [taichi-framework/TaiChi#1335]
Exception occurred while executing 'set-device-owner':
java.lang.IllegalStateException: Not allowed to set the device owner because there are already several users on the device.
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:9453)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:8388)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetDeviceOwner(DevicePolicyManagerServiceShellCommand.java:256)
        at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:89)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:9772)
        at android.os.Binder.shellCommand(Binder.java:970)
        at android.os.Binder.onTransact(Binder.java:854)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6952)
        at android.os.Binder.execTransactInternal(Binder.java:1226)
        at android.os.Binder.execTransact(Binder.java:1163)

**Comment by Nesxc** [comment]
ColorOS12

**Comment by Nesxc** [comment]
OPPO Reno3

**Comment by qingyuan0o0** [comment]
HuaWei Mate 30 5G  系统是鸿蒙
adb>adb shell dpm set-device-owner me.weishu.exp/.DeviceAdmin
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device
        at android.os.Parcel.createException(Parcel.java:2098)
        at android.os.Parcel.readException(Parcel.java:2058)
        at android.os.Parcel.readException(Parcel.java:2006)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392)
        at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:115)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:56)
        at com.android.commands.dpm.Dpm.main(Dpm.java:41)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(libmapleservices.so:14688372)
        at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(libmapleservices.so:16974700)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(libmapleframework.so:5783816)
        at com.android.server.devicepolicy.DevicePolicyManagerService.onTransact(libmapleservices.so:7467428)
        at android.os.Binder.execTransactInternal(libmapleframework.so:6255628)
callee: null 1530/2130
