### ISSUE TITLE
BUG：e c f

### ISSUE THREAD

**Issue by kwaiching** [taichi-framework/TaiChi#1360]
2023-01-25 12:59:39.245 15945-15945 ExposedBridge           com.ss.android.ugc.aweme.lite        E  e c f
                                                                                                    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ss.android.ugc.aweme.lite-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ss.android.ugc.aweme.lite-1/lib/arm, /data/app/com.ss.android.ugc.aweme.lite-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libexp82464.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1562)
                                                                                                    	at me.weishu.exposed.ExposedBridge.init(SourceFile:211)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.ss.android.ugc.aweme.app.host.AwemeHostApplication.<clinit>(SourceFile)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:993)
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5386)
                                                                                                    	at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1546)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6128)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by kwaiching** [comment]
Xiaomi/lineage_mido/mido:7.1.2
