### ISSUE TITLE
请求支持NEClient模块，比音量增强器稳定好用

### ISSUE THREAD

**Issue by akang1937** [taichi-framework/TaiChi#329]
## 模块安装包 
[xposed.leewp14.NEClient-2017.10-7-release.zip](https://github.com/taichi-framework/TaiChi/files/2884237/xposed.leewp14.NEClient-2017.10-7-release.zip)
压缩包内是apk安装包

**Comment by HaoyeTang** [comment]
支持的上古模块会越来越少的，毕竟网易云也在更新

**Comment by tiann** [comment]
```java
2019-02-21 10:11:52.082 13891-13891/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.netease.cloudmusic, PID: 13891
    java.lang.ExceptionInInitializerError
        at com.netease.cloudmusic.module.transfer.download.c.b(ProGuard:57)
        at com.netease.cloudmusic.module.transfer.download.a.<init>(ProGuard:115)
        at com.netease.cloudmusic.module.transfer.download.a.m(ProGuard:124)
        at com.netease.cloudmusic.fragment.cc.<init>(ProGuard:111)
        at com.netease.cloudmusic.activity.MainActivity$b.getItem(ProGuard:633)
        at android.support.v4.app.FragmentPagerAdapter.instantiateItem(ProGuard:101)
        at android.support.v4.view.ViewPager.addNewItem(ProGuard:1038)
        at android.support.v4.view.ViewPager.populate(ProGuard:1220)
        at android.support.v4.view.ViewPager.populate(ProGuard:1120)
        at android.support.v4.view.ViewPager.onMeasure(ProGuard:1646)
        at com.netease.cloudmusic.ui.NeteaseMusicViewPager.onMeasure(ProGuard:90)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23223)
        at android.support.v4.widget.DrawerLayout.onMeasure(ProGuard:1081)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ProGuard:139)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6753)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:737)
        at android.view.View.measure(View.java:23223)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2782)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1635)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1919)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1523)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7395)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
        at android.view.Choreographer.doCallbacks(Choreographer.java:877)
        at android.view.Choreographer.doFrame(Choreographer.java:808)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1051)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
```

模块出错了，如果作者不更新，单凭我这边很难处理。
