### ISSUE TITLE
Bug report: FGO BiliBili官服无限崩溃

### ISSUE THREAD

**Issue by xausky** [taichi-framework/TaiChi#432]
**Describe the bug**
FGO BiliBili官服使用太极安装后打开就立即崩溃

**To Reproduce**
1. 下载安装太极5.0.2
2. 下载FGO BiliBili官服：http://game.bilibili.com/fgo/
3. 使用太极添加FGO并且优化
4. 启动FGO
5. 立即看到崩溃提示

**Expected behavior**

解决崩溃问题，可以正常使用Xposed模块

**Smartphone (please complete the following information):**
Magisk version：无
TaiChi-Magisk module version：无
TaiChi version：5.0.2
Which Xposed modules are enabled ?：无
Xposed modules version：无
Which Magisk modules are enabled ?：无
Magisk modules version：无
Device ：OnePlus 3T
ROM：Android 8.0

**Additional context**

下面是我用ADB截取的关键崩溃日志：

```
03-05 13:20:26.311 14288 14288 E AndroidRuntime: FATAL EXCEPTION: main
03-05 13:20:26.311 14288 14288 E AndroidRuntime: Process: com.bilibili.fatego, PID: 14288
03-05 13:20:26.311 14288 14288 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application me.weishu.exposed.ExposedApplication: java.lang.ClassNotFoundException: Didn't find class "me.weishu.exposed.ExposedApplication" on path: DexPathList[[zip file "/data/app/com.bilibili.fatego--S2ZsePlR7I7nisvh6N3cQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.bilibili.fatego--S2ZsePlR7I7nisvh6N3cQ==/lib/arm, /system/fake-libs, /data/app/com.bilibili.fatego--S2ZsePlR7I7nisvh6N3cQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1011)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5997)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6798)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "me.weishu.exposed.ExposedApplication" on path: DexPathList[[zip file "/data/app/com.bilibili.fatego--S2ZsePlR7I7nisvh6N3cQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.bilibili.fatego--S2ZsePlR7I7nisvh6N3cQ==/lib/arm, /system/fake-libs, /data/app/com.bilibili.fatego--S2ZsePlR7I7nisvh6N3cQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1090)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:993)
03-05 13:20:26.311 14288 14288 E AndroidRuntime: 	... 9 more
```

**Comment by tiann** [comment]
帮忙试下这个是否已经修复：https://www.lanzous.com/i3c6bkh

**Comment by tiann** [comment]
https://github.com/taichi-framework/TaiChi/releases/tag/5.0.5
