### ISSUE TITLE
新增模块支持：【Device ID Masker Pro】

### ISSUE THREAD

**Issue by byqty** [taichi-framework/TaiChi#501]
## Module name
Device ID Masker Pro
## Usage

伪装设备信息

## Module version 
1.16
## APK file
谷歌:
https://play.google.com/store/apps/details?id=zone.bytesreverser.xposeddeviceidmasker
百度云:
https://pan.baidu.com/s/10vf-8QvKq5HRyejVI__Gwg 密码：qiwe

**Comment by cq535454518** [comment]
这个有破解版么？

**Comment by MoonBegonia** [comment]
> 这个有破解版么？

就算有你在太极也用不了

**Comment by byqty** [comment]
> 这个有破解版么？

我买了正版的，又不贵，老想着破解版干嘛……

**Comment by cq535454518** [comment]
> > 这个有破解版么？
> 
> 我买了正版的，又不贵，老想着破解版干嘛……

没有谷歌三件套，烦。。。。不想安装。我找找国内的吧！

**Comment by cq535454518** [comment]
> > 这个有破解版么？
> 
> 就算有你在太极也用不了

谁说我说太极。。。。。。。安卓7.1路过

**Comment by tiann** [comment]
```java
dlopen failed: "/data/data/zone.bytesreverser.xposeddeviceidmasker/app_outdex/libdexprotector.6i8bes.10778.so" is 32-bit instead of 64-bit (RmluZ2VycHJpbnQgMjAxODEyMjQgWysuLisuLl0gYXJtNjQtdjhhOmFybWVhYmktdjdhIDE5LzIuMS4wLy0gWGlhb21pL3BvbGFyaXMvcG9sYXJpczo5L1BLUTEuMTgwNzI5LjAwMS9WMTAuMi4yLjAuUERHQ05YTTp1c2VyL3JlbGVhc2Uta2V5cw==)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1073)
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.epic.art2.EpicNative.invoke(Native Method)
        at de.robv.android.xposed.ais.a(SourceFile:248)
        at de.robv.android.xposed.DexposedBridge.invokeOriginalMethod(SourceFile:538)
        at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:259)
        at de.robv.android.xposed.DexposedBridge.handleHookedArtMethod(SourceFile:205)
        at android.app.LoadedApk_1883340384.makeApplication(Unknown Source:16)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5916)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
似乎是插件自己的问题。
