### ISSUE TITLE
BUG：在更新内核或者是更新太极内核之后magisk太极会卡m 二屏

### ISSUE THREAD

**Issue by jerryliang122** [taichi-framework/TaiChi#653]
## 什么问题

在更新内核后，太极会卡mi2屏

## 详细情况

在官方内核修改为GitHub上的某内核后太极并不会卡mi2屏，如果此时刷回官方刷机包也就是官方内核后，便会卡在米2屏三点暗屏（将要进入桌面那段），反复无果。只能删除/data/system/taichi里的所有数据方可打开手机。

因配置文件删除后方可开机所以未保留该文件

Magisk 版本：18.1
太极 Magisk 模块版本：
太极APP版本：4.8.0
开启的 Xposed 模块：绿色守护，抖音，微x，qx，应用控制器，模拟位置
Xposed模块版本：4.6.3，2。3.0，2.0，1.21，3.2.6，1.2.681.1701
开启的其他 Magisk 模块：busybox,greenify,lkt,mm,scene,杜比
其他 Magisk 模块版本：（无）
手机型号：xiaomi mi 6
ROM版本：9.4.11

## 配置文件

请提供手机里面的 `/data/system/taichi/modules.list` 以及 `/data/system/taichi/apps.list` 文件。

补充：有能力请务必提供日志文件已快速解决问题。

**Comment by tiann** [comment]
能抓到日志吗？

**Comment by jerryliang122** [comment]
我应该可以在下一次出现这个问题的时候抓那两个文件

**Comment by tiann** [comment]
需要提供 logcat 日志，这两个文件在这个场景没有帮助

**Comment by jerryliang122** [comment]
可以告诉我这个日志应该如何抓取么

**Comment by tiann** [comment]
[logcat_v13.2.zip](https://github.com/taichi-framework/TaiChi/files/3084927/logcat_v13.2.zip)

刷入这个magisk模块，然后问题复现之后，把 `/data/local/boot`这个目录下的所有文件发给我。（可能需要在 rec 中拿）

**Comment by jerryliang122** [comment]
好的

**Comment by jerryliang122** [comment]
请问这个模块需要多长时间才能开机或者进入第二屏

**Comment by tiann** [comment]
什么意思？这个模块只是用来收集日志的。

**Comment by jerryliang122** [comment]
加载这个模块后手机卡在第一屏

**Comment by tiann** [comment]
仅仅加载这一个模块，不加载其他的都会卡第一屏？你的系统是 8.x 还是 9.0?

**Comment by jerryliang122** [comment]
8.x

**Comment by tiann** [comment]
执行 `rm -rf /data/system/taichi`，然后把这个日志模块删掉，看看能不能开机

**Comment by jerryliang122** [comment]
这个日志模块似乎已经生成了一个文件。一共5万行

**Comment by jerryliang122** [comment]
http://kd.jerryliang.top/file/phone/boot-1970-06-27-09-50-20.log 这是这个文件，现在按照 rm了那个文件夹+去除日志模块后启动了机器

**Comment by jerryliang122** [comment]
不过这个不影响使用，就是更新后会非常麻烦

**Comment by tiann** [comment]
可能是更新之后模块兼容性问题，不勾选  应用控制器 能正常开机吗？

**Comment by tiann** [comment]
#656 

试试这个 issue 里面的安装包。

**Comment by neoblackxt** [comment]
@tiann 哥们你技术很牛！！ChiMI 绿色守护 模拟位置都成功修复了，但是我发现了一个新问题，关于应用控制器的另一个错误，导致系统无法开机。
[logcat_sysPid1315_bootloop2die_seEnforcing_taichiV5.1.9.2-93_mmV4.8.0_应用控制器V3.2.6.log](https://github.com/taichi-framework/TaiChi/files/3090581/logcat_sysPid1315_bootloop2die_seEnforcing_taichiV5.1.9.2-93_mmV4.8.0_.V3.2.6.log)
5864行
```
04-18 00:18:57.571  1315  1315 W System.err: java.lang.NoSuchMethodError: com.android.server.NetworkManagementService(android.content.Context,java.lang.String)#exact
04-18 00:18:57.573  1315  1315 W System.err: 	at de.robv.android.xposed.XposedHelpers.findConstructorExact(SourceFile:614)
04-18 00:18:57.573  1315  1315 W System.err: 	at de.robv.android.xposed.XposedHelpers.findAndHookConstructor(SourceFile:627)
04-18 00:18:57.573  1315  1315 W System.err: 	at com.click369.controlbp.service.kc.a(XposedUtil.java:625)
04-18 00:18:57.573  1315  1315 W System.err: 	at com.click369.controlbp.service.bj.a(XposedAMS.java:2745)
04-18 00:18:57.573  1315  1315 W System.err: 	at com.click369.controlbp.service.ControlService.handleLoadPackage(ControlService.java:201)
04-18 00:18:57.573  1315  1315 W System.err: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(SourceFile:34)
04-18 00:18:57.573  1315  1315 W System.err: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(SourceFile:61)
04-18 00:18:57.573  1315  1315 W System.err: 	at de.robv.android.xposed.callbacks.XCallback.callAll(SourceFile:106)
04-18 00:18:57.573  1315  1315 W System.err: 	at me.weishu.exposed.ExposedBridge.a(SourceFile:840)
04-18 00:18:57.573  1315  1315 W System.err: 	at me.weishu.exposed.ExposedBridge.loadModule(SourceFile:781)
04-18 00:18:57.573  1315  1315 W System.err: 	at me.weishu.exposed.ExposedBridge.initNative(Native Method)
04-18 00:18:57.573  1315  1315 W System.err: 	at me.weishu.exposed.ExposedBridge.init(SourceFile:202)
04-18 00:18:57.573  1315  1315 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 00:18:57.573  1315  1315 W System.err: 	at me.weishu.taichi.MagiskInit.b(Unknown Source:292)
04-18 00:18:57.573  1315  1315 W System.err: 	at me.weishu.taichi.MagiskInit.a(Unknown Source:0)
04-18 00:18:57.573  1315  1315 W System.err: 	at me.weishu.taichi.MagiskInit$2.invoke(Unknown Source:61)
04-18 00:18:57.573  1315  1315 W System.err: 	at java.lang.reflect.Proxy.invoke(Proxy.java:913)
04-18 00:18:57.573  1315  1315 W System.err: 	at $Proxy0.addService(Unknown Source)
04-18 00:18:57.573  1315  1315 W System.err: 	at android.os.ServiceManager.addService(ServiceManager.java:88)
04-18 00:18:57.573  1315  1315 W System.err: 	at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2346)
04-18 00:18:57.573  1315  1315 W System.err: 	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:604)
04-18 00:18:57.573  1315  1315 W System.err: 	at com.android.server.SystemServer.run(SystemServer.java:409)
04-18 00:18:57.573  1315  1315 W System.err: 	at com.android.server.SystemServer.main(SystemServer.java:275)
04-18 00:18:57.573  1315  1315 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 00:18:57.573  1315  1315 W System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
04-18 00:18:57.573  1315  1315 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
04-18 00:18:57.573  1315  1315 I Xposed  : ^^^^^^^^^^^^^^构造函数未找到  com.android.server.NetworkManagementService  java.lang.NoSuchMethodError: com.android.server.NetworkManagementService(android.content.Context,java.lang.String)#exact^^^^^^^^^^^^^^^^^

```

7407行
```
--------- beginning of crash
04-18 00:18:58.918  1315  1315 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
04-18 00:18:58.918  1315  1315 E AndroidRuntime: java.lang.IllegalAccessError: Illegal class access: 'com.android.server.am.ActivityManagerService_530320990584' attempting to access 'com.android.server.am.ProcessRecord' (declaration of 'com.android.server.am.ActivityManagerService_530320990584' appears in Anonymous-DexFile@0x7b78cf2000-0x7b78cf252c)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService_530320990584.startProcessLocked(Unknown Source:90)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.startProcessLocked(ActivityManagerService.java:3776)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.am.ActiveServices.bringUpServiceLocked(ActiveServices.java:2287)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.am.ActiveServices.bindServiceLocked(ActiveServices.java:1500)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.bindService(ActivityManagerService.java:18953)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1612)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at android.app.ContextImpl.bindServiceAsUser(ContextImpl.java:1559)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.InputMethodManagerService.bindCurrentInputMethodService(InputMethodManagerService.java:1577)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.InputMethodManagerService.startInputInnerLocked(InputMethodManagerService.java:1914)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.InputMethodManagerService.systemRunning(InputMethodManagerService.java:1502)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.InputMethodManagerService$Lifecycle.onBootPhase(InputMethodManagerService.java:1255)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:152)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.SystemServer.lambda$-com_android_server_SystemServer_78745(SystemServer.java:1741)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.-$Lambda$T7cKu_OKm_Fk2kBNthmo_uUJTSo$4.$m$0(Unknown Source:98)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.-$Lambda$T7cKu_OKm_Fk2kBNthmo_uUJTSo$4.run(Unknown Source:0)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.systemReady(ActivityManagerService.java:14744)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1738)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:411)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:275)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
04-18 00:18:58.918  1315  1315 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```
7447行
```
04-18 00:18:58.924  1315  1315 D ActivityManager: report kill process: killerPid is:1315, killedPid is:1315
04-18 00:18:58.924  1315  1315 I Process : Sending signal. PID: 1315 SIG: 9
```

到这里system_server进程被杀死。似乎系统还在自动重试。但最后系统自动重启到recovery模式。

**Comment by jerryliang122** [comment]
唔 确认是应用控制器的问题导致无法开机

**Comment by tiann** [comment]
[taichi_5.1.9.3.apk.zip](https://github.com/taichi-framework/TaiChi/files/3092198/taichi_5.1.9.3.apk.zip)

试下这个呢？

**Comment by neoblackxt** [comment]
我这边测试没问题了。@jerryliang122

**Comment by neoblackxt** [comment]
[logcat_v13.2_mod_for_taichi.zip](https://github.com/taichi-framework/TaiChi/files/3099487/logcat_v13.2_mod_for_taichi.zip)
做了一点修改，改了输出格式，改成了每句占一行，顺便添加了apps.list和modules.list的输出。
**需要busybox的支持**

**Comment by jerryliang122** [comment]
kd.jerryliang.top/file/phone/boot-2019-04-20-10-59-04.log
我使用新的模块获取了日志。但是使用新版的5.1.9.3 使用之前的方法 无法复现问题了

**Comment by huitc** [comment]
+1  t.t
