### ISSUE TITLE
Bug report: Not allowed to set the device owner because there are already some accounts on the device

### ISSUE THREAD

**Issue by Sakitam1023** [taichi-framework/TaiChi#830]
**Describe the bug**
我无法通过adb开启阴阳之门，原因是我已经有一个account了，可是我并没有存在任何一个多余的账号

**To Reproduce**
1.我开启了开发模式，也开启了OEM解锁
2.当我使用 
> adb shell dpm set-device-owner me.weishu.exp/.DeviceAdmin

之后我会产生报错

```
java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device
        at android.os.Parcel.readException(Parcel.java:2021)
        at android.os.Parcel.readException(Parcel.java:1959)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:5176)
        at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:148)
        at com.android.commands.dpm.Dpm.onRun(Dpm.java:96)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
        at com.android.commands.dpm.Dpm.main(Dpm.java:41)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
```
3.之后我查看我当前的users
```
C:\Users\tjwsq\Desktop\bootloader\vivo_fastboot\vivo_fastboot>adb shell pm list users
Users:
        UserInfo{0:鏈轰富:13} running

```

**Expected behavior**
我需要得到Success的结果

**Smartphone**
Magisk version：未安装
TaiChi-Magisk module version：未安装
TaiChi version：Version: 东皇钟 · 5.2.0-263
Which Xposed modules are enabled ?：未安装
Xposed modules version：未安装
Which Magisk modules are enabled ?：未安装
Magisk modules version：未安装
Device ：Vivo z3
ROM：6G + 64G

**Comment by elvismacak** [comment]
It's because some accounts are not displayed in 'Settings > Account'. Last time, I meet the same problem ,  Alipay hold an account but disappear in settings, just uninstall it, it's ok.

You can run `adb shell dumpsys 2>/dev/null | grep  Accounts  -w -A 1  info | grep Account -w` to display all the account, and uninstall the related app.

**Comment by pssyz** [comment]
> It's because some accounts are not displayed in 'Settings > Account'. Last time, I meet the same problem , Alipay hold an account but disappear in settings, just uninstall it, it's ok.
> 
> You can run `adb shell dumpsys 2>/dev/null | grep Accounts -w -A 1 info | grep Account -w` to display all the account, and uninstall the related app.

getting success by uninstalling Alipay , thx
