### ISSUE TITLE
BUG：使用Yandex浏览器时崩溃、Yandex浏览同步崩溃

### ISSUE THREAD

**Issue by fjyuqiang** [taichi-framework/TaiChi#999]
## 什么问题

使用Yandex浏览器崩溃

## 详细情况

1. 正常安装太极·阳，打开全局模式
2. 打开Yandex broswer，提示几次崩溃
3. 点击Yandex broswer中的同步，再次提示崩溃
4. 一段时间后正常，不在提示
5. 在全局模式中把Yandex broswer加入白名单，还是会出现step2-step4
6. 如果杀死Yandex broswer后台，重复出现step2-step4
7. 卸载太极Magisk后不再提示

Magisk 版本：v20.0
太极 Magisk 模块版本：v5.1.4
太极APP版本：v5.5.8
开启的 Xposed 模块：【绿色守护】、【假装分享】、【MyAndroidToolsXposed】、【AD快消】、【QX模块】、【微信群消息助手】、【微信增强】、【3000模块】
Xposed模块版本：【v4.7.5】、【v-126】、【v0.8】、【v1.4.9】、【v2.1】、【v1.4.5】、【v1.9.1】、【v14.27】
开启的其他 Magisk 模块：【APP Sysytemizer】、【Busybox for Android NDK】、【LKT】、【Magisk Manager for Recovery Mode】、【Tai Chi】、【Universal GMS Doze】、【Wifi Bonding】
其他 Magisk 模块版本：（无）
手机型号：Xiaomi Mi MIX3
ROM版本：MIUI 11 9.9.26

## 期望

安装太极magisk下可以正常使用Yandex Broswer的同步功能，不再提示崩溃

## 配置文件

[modules.list.txt](https://github.com/taichi-framework/TaiChi/files/3770290/modules.list.txt)
[apps.list.txt](https://github.com/taichi-framework/TaiChi/files/3770291/apps.list.txt)

## 补充：崩溃日志

java.lang.RuntimeException: Unable to create application com.yandex.browser.YandexBrowserApplication: java.lang.IllegalStateException: allowBackup='true' is not allowed
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5964)
	at android.app.ActivityThread.access$1200(ActivityThread.java:201)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1674)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6820)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.IllegalStateException: allowBackup='true' is not allowed
	at com.yandex.passport.a.S.a(SourceFile:25)
	at com.yandex.passport.a.S.f(SourceFile:3)
	at com.yandex.passport.a.S.a(SourceFile:7)
	at com.yandex.passport.a.L.a(SourceFile:22)
	at com.yandex.passport.a.L.a(SourceFile:41)
	at com.yandex.passport.api.Passport.initializePassport(SourceFile:1)
	at com.yandex.browser.YandexBrowserApplication.onCreate(SourceFile:190)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5959)
	... 8 more

## 详细崩溃日志

[log.txt](https://github.com/taichi-framework/TaiChi/files/3770293/log.txt)

**Comment by tiann** [comment]
你把相关模块都关掉再试试看，从日志看这个跟太极本身没有关系。

**Comment by fjyuqiang** [comment]
## 试了如下几个方法：

1. 太极开全局模式，白名单中添加Yandex，报错×
2. 在1的基础上，逐一关掉各个模块，都是报错×
3. 更换了Yandex的v19.7，报错×
4. 在magisk中关掉太极模块，正常√

补充：
反编译Yandex的包，Application 里的属性是android:allowBackup="false"，和log中不一样

**Comment by tiann** [comment]
你把太极中使用的模块全部关掉再看看，不是关面具模块。

**Comment by fjyuqiang** [comment]
已经尝试过全部模块关掉了。还是会报错

**Comment by fjyuqiang** [comment]
目前暂时修复了，卸载了面具里的Uniserval GMS Doze 模块，不再出现这个提示了
